version: "3"
volumes:
  mysql_8_0-data:
  redis-data:
  vendor_bundle_2_5_1:
  vendor_assets_2_7:
  node_modules:
  public_spree_2_7:

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - default
    ports:
      - '33306:3306'
    volumes:
      - mysql_8_0-data:/var/lib/mysql
  redis:
    image: redis:alpine
    networks:
      - default
    ports:
      - '36379:6379'
    volumes:
      - redis-data:/var/lib/redis
  potepanec:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: mysql
      REDIS_URL: "redis://redis:6379"
    depends_on:
      - mysql
      - redis
    networks:
      - default
    volumes:
      - .:/potepanec
      # https://qiita.com/shotat/items/57d049793605ffc20135
      - /potepanec/log
      - /potepanec/tmp
      #- /potepanec/vendor/bundle
      - vendor_bundle_2_5_1:/potepanec/vendor/bundle
      - vendor_assets_2_7:/potepanec/vendor/assets
      - node_modules:/potepanec/node_modules
      - public_spree_2_7:/potepanec/public/spree
    tty: true
    stdin_open: true
    command: bundle exec rails server -p 3000 -b 0.0.0.0
